server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
db.connection.retry.max_attempts: 4
db.connection.retry.backoff_ms: 800